name: Pipeline de CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      #- name: Validar HTML
      #  run: |
      #    if ! grep -q "<html" site/index.html; then
      #      echo "HTML inválido"
      #      exit 1
      #    fi

      - name: Criar artefato
        run: |
          rm -rf build
          mkdir build
          cp site/index.html build/

      - name: Publicar artefato
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: build


